In [6]:
import pandas as pd

In [3]:
print(pd.__version__)

2.3.3

In [4]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [13]:
# series 
house_numbers = [12,34,56,78,90,11,22]
series_data = pd.Series(house_numbers, index={"A1","A2","A3","A4","A5","A6","A7"})
series_data

A1    12
A3    34
A5    56
A2    78
A6    90
A7    11
A4    22
dtype: int64

In [14]:
series_data.info()

<class 'pandas.core.series.Series'>
Index: 7 entries, A1 to A4
Series name: None
Non-Null Count  Dtype
--------------  -----
7 non-null      int64
dtypes: int64(1)
memory usage: 412.0+ bytes

In [17]:
series_data.describe()

count     7.000000
mean     43.285714
std      31.909843
min      11.000000
25%      17.000000
50%      34.000000
75%      67.000000
max      90.000000
dtype: float64

In [16]:
print(series_data *2)

A1     24
A3     68
A5    112
A2    156
A6    180
A7     22
A4     44
dtype: int64

In [22]:
# dataframe
utils = {
    "items": ['pen', 'book','bag'],
    "price": [20,150,900],
    "stock": [100,40,12],
}

In [27]:
df = pd.DataFrame(utils, index=['A1','A2','A3'])

df.head()

   items  price  stock
A1   pen     20    100
A2  book    150     40
A3   bag    900     12

In [28]:
df.tail()

   items  price  stock
A1   pen     20    100
A2  book    150     40
A3   bag    900     12

In [31]:
print(df.shape)

(3, 3)

In [1]:
text = """name,age,city,maths,english,science
Ali,16,Lahore,80,72,91
Sara,15,Karachi,65,88,70
Hassan,17,Lahore,95,60,84
Ayesha,16,Islamabad,72,,78
Bilal,15,Karachi,55,64,
Fatima,16,Lahore,88,91,95
Usman,17,Islamabad,,58,62
Zainab,15,Karachi,92,85,89
Hamza,16,Lahore,45,50,48
Maryam,17,Islamabad,78,80,
"""

In [2]:
with open("students.csv", "w") as f:
    f.write(text)

In [7]:
df = pd.read_csv("students.csv")

In [8]:
df

     name  age       city  maths  english  science
0     Ali   16     Lahore   80.0     72.0     91.0
1    Sara   15    Karachi   65.0     88.0     70.0
2  Hassan   17     Lahore   95.0     60.0     84.0
3  Ayesha   16  Islamabad   72.0      NaN     78.0
4   Bilal   15    Karachi   55.0     64.0      NaN
5  Fatima   16     Lahore   88.0     91.0     95.0
6   Usman   17  Islamabad    NaN     58.0     62.0
7  Zainab   15    Karachi   92.0     85.0     89.0
8   Hamza   16     Lahore   45.0     50.0     48.0
9  Maryam   17  Islamabad   78.0     80.0      NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     10 non-null     object
 1   age      10 non-null     int64
 2   city     10 non-null     object
 3   maths    9 non-null      float64
 4   english  9 non-null      float64
 5   science  8 non-null      float64
dtypes: float64(3), int64(1), object(2)
memory usage: 608.0+ bytes

In [14]:
df.iloc[0]

name          Ali
age            16
city       Lahore
maths        80.0
english      72.0
science      91.0
Name: 0, dtype: object

In [18]:
df.iloc[0:3]

     name  age     city  maths  english  science
0     Ali   16   Lahore   80.0     72.0     91.0
1    Sara   15  Karachi   65.0     88.0     70.0
2  Hassan   17   Lahore   95.0     60.0     84.0

In [28]:
df.loc[0, ['name','english','maths']]

name        Ali
english    72.0
maths      80.0
Name: 0, dtype: object