In [2]:
import pandas as pd
import numpy as np

In [4]:
students_text = """student_id,name,city,maths,english,science
1,Ali,Lahore,80,72,91
2,Sara,Karachi,65,88,70
3,Hassan,Lahore,95,60,84
4,Ayesha,Islamabad,72,76,78
5,Bilal,Karachi,55,64,58
6,Fatima,Lahore,88,91,95
7,Usman,Islamabad,66,58,62
8,Zainab,Karachi,92,85,89
9,Hamza,Lahore,45,50,48
10,Maryam,Islamabad,78,80,74
11,Imran,Karachi,70,68,72
12,Hira,Islamabad,85,90,88
"""
fees_text = """student_id,fee_paid,fee_amount
1,Yes,5000
2,Yes,5000
3,No,5000
5,Yes,4000
6,Yes,5000
7,No,4000
8,Yes,5000
9,No,4000
10,Yes,5000
11,Yes,4000
13,Yes,5000
"""

with open("students.csv", "w") as f:
    f.write(students_text)
with open("fees.csv", "w") as f:
    f.write(fees_text)

df = pd.read_csv("students.csv")
fees = pd.read_csv("fees.csv")

In [5]:
print(df.groupby("city")['maths'].mean())

city
Islamabad    75.25
Karachi      70.50
Lahore       77.00
Name: maths, dtype: float64

In [6]:
print(df.groupby('city')['science'].mean())

city
Islamabad    75.50
Karachi      72.25
Lahore       79.50
Name: science, dtype: float64

In [12]:
print(df.groupby('city')['science'].max())

city
Islamabad    88
Karachi      89
Lahore       95
Name: science, dtype: int64

In [7]:
print(df.groupby('city').size())

city
Islamabad    4
Karachi      4
Lahore       4
dtype: int64

In [ ]:
print(df.groupby("city")["maths"].agg(["mean", "min", "max"]))

            mean  min  max
city
Islamabad  75.25   66   85
Karachi    70.50   55   92
Lahore     77.00   45   95

In [6]:
print(df.groupby("city")[["maths", "english", "science"]].agg(['mean','min','max']))

           maths         english         science
            mean min max    mean min max    mean min max
city
Islamabad  75.25  66  85   76.00  58  90   75.50  62  88
Karachi    70.50  55  92   76.25  64  88   72.25  58  89
Lahore     77.00  45  95   68.25  50  91   79.50  48  95

In [8]:
both = pd.merge(df,fees , on='student_id')
both

   student_id    name       city  maths  english  science fee_paid  fee_amount
0           1     Ali     Lahore     80       72       91      Yes        5000
1           2    Sara    Karachi     65       88       70      Yes        5000
2           3  Hassan     Lahore     95       60       84       No        5000
3           5   Bilal    Karachi     55       64       58      Yes        4000
4           6  Fatima     Lahore     88       91       95      Yes        5000
5           7   Usman  Islamabad     66       58       62       No        4000
6           8  Zainab    Karachi     92       85       89      Yes        5000
7           9   Hamza     Lahore     45       50       48       No        4000
8          10  Maryam  Islamabad     78       80       74      Yes        5000
9          11   Imran    Karachi     70       68       72      Yes        4000

In [14]:
left = pd.merge(df, fees, on="student_id", how="left")
print(left)
left.head()

    student_id    name       city  maths  english  science fee_paid  \
0            1     Ali     Lahore     80       72       91      Yes
1            2    Sara    Karachi     65       88       70      Yes
2            3  Hassan     Lahore     95       60       84       No
3            4  Ayesha  Islamabad     72       76       78      NaN
4            5   Bilal    Karachi     55       64       58      Yes
5            6  Fatima     Lahore     88       91       95      Yes
6            7   Usman  Islamabad     66       58       62       No
7            8  Zainab    Karachi     92       85       89      Yes
8            9   Hamza     Lahore     45       50       48       No
9           10  Maryam  Islamabad     78       80       74      Yes
10          11   Imran    Karachi     70       68       72      Yes
11          12    Hira  Islamabad     85       90       88      NaN

    fee_amount
0       5000.0
1       5000.0
2       5000.0
3          NaN
4       4000.0
5       5000.0
6       4000.0
7       5000.0
8       4000.0
9       5000.0
10      4000.0
11         NaN

   student_id    name       city  maths  english  science fee_paid  fee_amount
0           1     Ali     Lahore     80       72       91      Yes      5000.0
1           2    Sara    Karachi     65       88       70      Yes      5000.0
2           3  Hassan     Lahore     95       60       84       No      5000.0
3           4  Ayesha  Islamabad     72       76       78      NaN         NaN
4           5   Bilal    Karachi     55       64       58      Yes      4000.0

In [11]:
right = pd.merge(df,fees, on='student_id', how='right')
right

,student_id,name,city,maths,english,science,fee_paid,fee_amount
0,1,Ali,Lahore,80.0,72.0,91.0,Yes,5000
1,2,Sara,Karachi,65.0,88.0,70.0,Yes,5000
2,3,Hassan,Lahore,95.0,60.0,84.0,No,5000
3,5,Bilal,Karachi,55.0,64.0,58.0,Yes,4000
4,6,Fatima,Lahore,88.0,91.0,95.0,Yes,5000
5,7,Usman,Islamabad,66.0,58.0,62.0,No,4000
6,8,Zainab,Karachi,92.0,85.0,89.0,Yes,5000
7,9,Hamza,Lahore,45.0,50.0,48.0,No,4000
8,10,Maryam,Islamabad,78.0,80.0,74.0,Yes,5000
9,11,Imran,Karachi,70.0,68.0,72.0,Yes,4000
10,13,NaN,NaN,NaN,NaN,NaN,Yes,5000

In [13]:
df["result"] = np.where(df["average"] >= 60, "Pass", "Fail")
print(df[["name", "average", "result"]])

KeyError: 'average'